Jahia/graphql-core

graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/DXGraphQLExtensionsProvider.java
graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/DXGraphQLProvider.java
graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/sdl/SDLConstants.java
graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/sdl/extension/PropertyFetcherExtensionInterface.java
graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/sdl/parsing/FetcherDirectiveWiring.java
graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/sdl/parsing/SDLRuntimeWiring.java
graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/sdl/parsing/SDLSchemaService.java
graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/sdl/parsing/SDLTypeChecker.java
graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/sdl/parsing/status/SDLDefinitionStatus.java
graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/sdl/parsing/status/SDLDefinitionStatusType.java

Branch used for developing new functionalities for the SDL API, allowing to declare custom fetchers, like this example from cloudinary-integration module
extend type ImageAsset {
cloudinary: CloudinaryAsset
}
"""
Addon for Cloudinary integration
"""
type CloudinaryAsset {
"""Public identifier for Cloudinary account (null if Cloudinary settings is not configured)"""
cloudspace: String @fetcher(name: "cloudinaryFetcher")
"""Path of the asset in Cloudinary (null if Cloudinary settings is not configured)"""
path: String @fetcher(name: "cloudinaryFetcher")
"""Upload url for this asset (null if Cloudinary settings is not configured)"""
url: String @fetcher(name: "cloudinaryFetcher")
}

BACKLOG-10433/MOD-1881

---

graphql-test/pom.xml
graphql-test/src/main/java/org/jahia/test/graphql/GraphQLPublicationTest.java

https://jira.jahia.org/browse/BACKLOG-15343
Fix race condition that's happening on GraphQLPublicationTest
Note:
Same pr as https://github.com/Jahia/graphql-core/pull/88/files

BACKLOG-15343-jahia-7.3: Fix race condition on GraphQLPublicationTest

---

graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/admin/GqlAdminQuery.java
graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/admin/GqlJahiaVersion.java

-Add more nodes to the admin node in graphql
-Deprecated old version node
https://jira.jahia.org/browse/BACKLOG-15726
Today our admin node returns the full Jahia version which requires some parsing on the client-side to fetch relevant information.
Before:
```GraphQL
{
"data": {
"admin": {
"version": "Jahia 8.0.3.0 [Indigo] - Build 61002"
}
}
}
```
After changes:
```GraphQL
{
"data": {
"admin": {
"version": "Jahia 8.0.2.0 - Enterprise Distribution",
"jahia": {
"release": "8.0.0.0",
"build": "60910",
"buildDate": "2021-02-02T17:08:30.000-05:00",
"isSnapshot": false
},
"datetime": "2021-03-16T15:36:42.902-04:00"
}
}
}
```

Backlog 15726 - Adding more nodes to the admin node in graphql

---

.circleci/config.yml
tests/warmup-manifest-build.yml
tests/warmup-manifest-release.yml

Update the config to fix the nightly executions. As the test module is linked to the Jahia version the matrix configuration cannot work for that, as we need to retrieve the snapshot or the release version of the module which cannot be done in the warmup. That's why I've updated the workflow.

Update CircleCI nightly config

---

.circleci/config.yml

The integration were explicitly using the 8.0.1.0-SNAPSHOT image. As we use this version to get the jahia-test-module it will stop working as soon as the artifacts will be clean-up in Nexus

Remove call to specific snapshot version in int. tests

---

graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/admin/GqlJahiaVersion.java

Simply adding graphql description to JahiaVersion Node
https://jira.jahia.org/browse/BACKLOG-15758
Before:
We have a missing description in recent API changes.
You can easily find it by looking at the schema which is fetch by graphql playground (look via dev console) when you open it up on a Jahia instance.
Then search for: GqlJahiaVersion
After Change:

Adding description to jahiaVersion node

---

graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/admin/GqlAdminQuery.java

Fixing Jahia version retrieving from "property" file
https://jira.jahia.org/browse/BACKLOG-15726
The release is incorrect, it does not match the version (and should be 8.0.2.0)

Fixing Java Version

---

.circleci/config.yml

It appeared that some quotes were causing issues in Testrail or Jahia. They were not removed when I moved from matrix to non-matrix config

Remove the double quotes in the nightly config

---

tests/warmup-manifest-snapshot.yml

After a couple of failing nightly runs I figured out that the warmup file (for snapshot) was missing the steps to deploy the downloaded assets

Add missing steps to deploy the downloaded artifacts

---

graphql-dxm-provider/pom.xml
graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/DXGraphQLProvider.java
graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/admin/AdminMutationExtensions.java
graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/admin/AdminQueryExtensions.java
graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/admin/GqlAdminMutation.java
graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/admin/GqlAdminQuery.java
graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/security/GqlJcrPermissionChecker.java
graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/security/GraphQLFieldWithPermissionRetriever.java
graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/security/GraphQLRequiresPermission.java
graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/user/GqlPrincipal.java
graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/user/GqlUser.java
graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/user/UserAdminExtension.java
tests/cypress/integration/api/admin/user.spec.ts

https://jira.jahia.org/browse/BACKLOG-16000
Allow to use @GraphQLRequiresPermission on any gql field, to specify which permission to check , instead of filling a cfg file. Can also specify target node by adding the path after the permission name.
Restored "query/admin/jahia" field, restricted to server administrators only. query/admin and mutation/admin are visible to all privileged users.

BACKLOG-16000: Add annotation to setup permission configuration, restore admin fields (#120)

---

.circleci/config.yml
graphql-dxm-provider/pom.xml
graphql-extension-example/pom.xml
graphql-test/pom.xml
pom.xml

https://jira.jahia.org/browse/BACKLOG-16198
reverted unsuccessful release of graphql-dxm-provider 2.6.0 and change the path to target folder of graphql-dxm-provider

BACKLOG-16198 fix target jr path and revert the version

---

graphql-dxm-provider/pom.xml

Update graphql-dxm-provider signature
Update the signature manually as circleci job failed due to the unique project structure

BACKLOG-16198 update signature as circleci job failed to do so

---

graphql-dxm-provider/pom.xml
graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/instrumentation/JCRInstrumentation.java
graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/predicate/FieldEvaluator.java
graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/render/RenderNodeExtensions.java
graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/util/ContextUtil.java

https://jira.jahia.org/browse/BACKLOG-16333
Previous version was using Optional in context to see if a request/response was present. Now, if servlet is called without request/response, context is a different object type.

BACKLOG-16333: handle the cases when context is not a servlet context

---

graphql-test/src/main/java/org/jahia/test/graphql/GraphQLNodeMutationsTest.java
graphql-test/src/main/java/org/jahia/test/graphql/GraphQLTestSupport.java
graphql-test/src/main/java/org/jahia/test/graphql/context/CustomGraphQLServletContext.java

https://jira.jahia.org/browse/TECH-210
Fix GraphQL mutation upload test
I've explored multiple ways of fixing the tests. One is the current way of injecting the file to test into the GraphQL context. Fixed by creating a custom GraphQL context and ContextBuilder to be able to inject into the service, and wrap old FileItem into a javax.http.servlet.Part instance.
I've also tried another route of creating a Multipart request that attaches file contents but had some issue with having both file content and the query request (it wasn't obvious how both are attached and probably needs further exploration later). I've kept the code as separate functions but not used just in case we want to continue exploring that path later on.

TECH-210: Fix graphql file mutation test

---

graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/DXGraphQLError.java
graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/JahiaDataFetchingExceptionHandler.java

Servlet is now using a dedicated method to serialize the error, instead of jackson.
A new ErrorClassification has been added and is more fexible than the previous error type, which allows us to directly return the value we want in `getErrorType` and get rid of `getRealErrorType`

BACKLOG-16328: Fixed error handling, add errorType in return

---

graphql-dxm-provider/pom.xml
graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/DXGraphQLProvider.java
graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/osgi/OSGIServiceInjectorDataFetcher.java
graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/security/GraphQLAsync.java
graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/security/JahiaGraphQLFieldRetriever.java

https://jira.jahia.org/browse/TECH-268
New @GraphQLAsync annotation will transform the datafetcher into async, using custom executor. Executor handle user/scopes so that permissions can be correctly checked.
OSGI injector fixed to work with async datafetcher.

TECH-268: Add annotation to create AsyncDataFetcher

---

graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/AggregateDataFetchingException.java
graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/JahiaDataFetchingExceptionHandler.java
graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/node/GqlJcrQuery.java
graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/upload/UploadHelper.java
graphql-test/src/main/java/org/jahia/test/graphql/GraphQLNodeMutationsTest.java
graphql-test/src/main/java/org/jahia/test/graphql/GraphQLSchedulerTest.java
graphql-test/src/main/java/org/jahia/test/graphql/GraphQLTestSupport.java
graphql-test/src/main/java/org/jahia/test/graphql/context/CustomGraphQLServletContext.java
graphql-test/src/main/java/org/jahia/test/graphql/utils/TestFileUtils.java

https://jira.jahia.org/browse/TECH-210
* Add support for multiple GraphQL errors through DataFetchingException (not sure if there's a better solution through contexts or through graphql.execution.DataFetcherResult)
* Fix upload file tests
* Disable subscription test

TECH-210: Add support for multiple GraphQL errors; Fix tests

---

graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/JahiaSubscriptionExecutionStrategy.java

https://jira.jahia.org/browse/QA-13889
When using websocket, session stays open and keeps a potentially invalid cache, crashing request when it is reused

QA-13889: close sessions opened when creating a subscription

---

.circleci/config.yml

Attempt to fix them with https://github.com/Jahia/graphql-core/pull/153

Disable Maven integration tests as config is unstable

---

graphql-test/src/main/resources/META-INF/spring/mod-graphql-test.xml

https://jira.jahia.org/browse/BACKLOG-16502
Already replaced the test with https://github.com/Jahia/graphql-core/pull/200, but missed this removal

BACKLOG-16502: remove GraphQLFieldSorterTest

---

graphql-test/src/main/resources/META-INF/spring/mod-graphql-test.xml

https://jira.jahia.org/browse/BACKLOG-16506
Removed the graphql test from the xml list.

BACKLOG-16506_remove : remove test in xml

---

graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/site/GqlJcrSite.java

https://jira.jahia.org/browse/QA-13998
Add homePage field on Site query to get the home page node
example:
```
jcr {
nodeByPath(path: $path) {
site {
homePage {
name
path
}
}
}
}
```

QA-13998 : add field to get homepage for a site

---

.github/workflows/on-release.yml

Some of the more complex builds require us to use our self-hosted runner to provide more CPU/RAM

BACKLOG-17102: Moved release runner to self-hosted

---

graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/node/GqlJcrNodeImpl.java

https://jira.jahia.org/browse/BACKLOG-20385
EDP implementation will throw UnsupportedRepositoryOperationExceptionrationException when calling getReferences (ignore exception). Split calls between weak and non weak references to ensure both calls are executed on EDP

BACKLOG-20385: EDP implementation will throw UnsupportedRepositoryOperationException

---

.github/workflows/on-code-change.yml
tests/package.json
tests/reporter-config.json
tests/yarn.lock

Following the merge of https://github.com/michaelleeallen/mocha-junit-reporter/pull/163 and the subsequent release of the npm package.

CI/CD: Updated the junit reporter used by Cypress

---

graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/util/ZipUtils.java

https://jira.jahia.org/browse/QA-14640
Prevent StringIndexOutOfBoundsException with fabricated ZIP files

QA-14640: Prevent StringIndexOutOfBoundsException

---

graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/util/ZipUtils.java

https://jira.jahia.org/browse/QA-14647
Don't take returned filename, which is OS path separator based

QA-14647: Don't take returned filename, which is OS path separator based

---

graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/node/GqlJcrNodeImpl.java
graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/predicate/FieldEvaluator.java

https://jira.jahia.org/browse/SUP-233
Issue was originally introduced by BACKLOG-20469 (graphql 2.15.0). If a referenceInField points to a non existing property, it fills a null property. If for any reason a null property is added to the results, it crashes the filter - so we need to avoid putting null in there.
Also added a check in getFieldValue to avoid the npe if source is null.

SUP-233: Prevent npe issues with broken references

---

graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/admin/GqlAdminQuery.java
graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/admin/GqlCluster.java
graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/admin/GqlJahiaAdminQuery.java
graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/admin/GqlJahiaDatabase.java
graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/admin/GqlJahiaSystem.java
graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/admin/GqlJahiaSystemJava.java
graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/admin/GqlJahiaSystemOs.java
graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/admin/GqlJahiaSystemProperty.java
tests/cypress/e2e/api/admin/cluster.cy.ts
tests/cypress/e2e/api/admin/database.cy.ts
tests/cypress/e2e/api/admin/system.cy.ts
tests/cypress/fixtures/admin/cluster.graphql
tests/cypress/fixtures/admin/database.graphql
tests/cypress/fixtures/admin/system.graphql

Here's a sample query with the new fields:
```graphql
{
admin {
jahia {
database {
type
name
version
driverName
driverVersion
url
}
system {
property(key: "karaf.remoteShellPort") {
key
value
}
os {
name
architecture
version
}
java {
runtimeName
runtimeVersion
vendor
vendorVersion
}
}
}
cluster {
isActivated
}
}
}
```
Sample response:
```json
{
"data": {
"admin": {
"jahia": {
"database": {
"type": "derby",
"name": "Apache Derby",
"version": "10.14.2.0 - (1828579)",
"driverName": "Apache Derby Embedded JDBC Driver",
"driverVersion": "10.14.2.0 - (1828579)",
"url": "jdbc:derby:directory:/var/jahia/jahiadb"
},
"system": {
"property": {
"key": "karaf.remoteShellPort",
"value": "8101"
},
"os": {
"name": "Linux",
"architecture": "amd64",
"version": "5.4.0-1045-aws"
},
"java": {
"runtimeName": …
```

BACKLOG-20609: Adding more nodes to fetch system information

---

graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/user/PrincipalInput.java
tests/cypress/e2e/api/acl/aclEntries.cy.ts

https://jira.jahia.org/browse/BACKLOG-20612
- Need to search global groups if not found within site
- Added cypress test case for global groups

BACKLOG-20612: Fix global lookup for users/groups on aclEntries endpoint

---

graphql-dxm-provider/.gitignore
graphql-dxm-provider/package.json
graphql-dxm-provider/yarn.lock

https://jira.jahia.org/browse/SEC-52
- Patched `browserify-sign` version (indirect dependency from `node-polyfill-webpack-plugin`) 
- Also moved `node-polyfill-webpack-plugin` to dev dependency (used for webpack)

SEC-52: Bump browserify-sign dev dependency

---

graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/node/GqlJcrNode.java
graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/node/GqlJcrNodeImpl.java

https://jira.jahia.org/browse/QA-15005
Adding an isExternal field on GqlJCRNode to know if a node is external or not. This will allow to hide/show actions in UI once useNodeChecks and UseNodeInfo are updated in data-helper

QA-15005: Add GraphQL field to know if node is external (has in not under the default provider)

---

graphql-dxm-provider/package.json
graphql-dxm-provider/pom.xml
graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/sdl/parsing/SDLSchemaService.java
graphql-extension-example/pom.xml
graphql-extension-example/src/main/resources/META-INF/graphql-extension.sdl
graphql-test/pom.xml
pom.xml

https://jira.jahia.org/browse/TECH-1597
Also fixed an issue relating to incorrect signature on graphql-extension-example which revealed (multiple) issues relating to directives and SDL extensions not working (still being investigated; creating a new ticket). 
For now we explicitly declare `@mapping` directive in the graphql-extension.sdl to workaround install issues but SDL types/queries are still not available.
Fixed one of the issues relating to graphql-java upgrade that is throwing exceptions.
In graphql-java v21, the code:
```ObjectTypeExtensionDefinition.getFieldDefinitions().removeAll(fieldDefinitions)``` now throws an exception as `getFieldDefinitions()` is now returning an immutable list. This throws an exception when calling `removeAll()` and is corrupting the schema. Needed to …

TECH-1597: Bump graphql version to 3.0.0; install workarounds for SDL extension issues

---

tests/cypress/e2e/api/apiDescription.cy.ts
tests/package.json
tests/yarn.lock

Some nodes were missing in the previous implementation. The logic of fetching descriptions was moved to jahia-cypress.
This new test suite also verified the presence of deprecation messages.

TECH-1631: Updated the tests for GraphQL API descriptions

---

graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/config/DXGraphQLConfig.java
graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/relay/PaginationHelper.java
graphql-dxm-provider/src/main/resources/META-INF/configurations/org.jahia.modules.graphql.provider-default.cfg

* QA-15096: Enforce limit of 5000 nodes for one page. Log messages over 500
* QA-15096: Add stack trace and use an AtomicInteger for node limit
* QA-15096: Ensure node limit can be set only on default file
(cherry picked from commit 9ec98610993e731378fee1ee737b4e6073f35485)
https://jira.jahia.org/browse/ QA-15096
Port from 2_x

QA-15096: Enforce limit of 5000 nodes for one page. Log messages over 500 (#401)

---

graphql-dxm-provider/src/main/resources/tools/developer/sdlreporttool.jsp

https://jira.jahia.org/browse/BACKLOG-22395
As mentionned in the ticket a strang import fo sping webflow packages has been detected and it was due to a elvariable declaration in a jsp. After removing that declaration (it was not used) the Import is not present anymore in MANIFEST neither in the OSGI wiring (inspected using tool)
I have considered the following implications of my change: 
N/A

BACKLOG-22395: Remove unused jsp elvariable declaration to fix MANIFEST

---

graphql-dxm-provider/src/main/resources/META-INF/graphql-extension.sdl

This reverts commit 5180107f368504979d1831e2e547e384156f116e.
https://jira.jahia.org/browse/BACKLOG-22388
Original PR was created to fix an issue around graphql version upgrade https://github.com/Jahia/graphql-core/pull/353 
Reverting as it could be a breaking change that's not necessarily needed for 2.20 (We do not have the graphql version upgrade in 2.20).

Revert "BACKLOG-21747 Update type in sdl (#353)"

---

graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/publication/GqlPublicationEvent.java
graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/publication/PublicationJobEventListener.java
graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/publication/PublicationJobSubscriptionExtension.java

https://jira.jahia.org/browse/TECH-1634
Publish service from the core will broadcast unpublished event once unpublishing is done, it can happen on any node.
This API will notify all the user subscribed

TECH-1634: Listen and notify about unpublished jobs (technically not background jobs)

---

.github/workflows/schedule-sonar.yml

https://jira.jahia.org/browse/TECH-1658
Use JDK image prefilled with the Jahia Maven cache for Sonar build analysis

TECH-1658: Use jahia image with prefilled with Maven cache

---

.github/dependabot.yml

We don't want the bot to create PR anymore

Disable dependabot PR creation

---

graphql-test/pom.xml

https://jira.jahia.org/browse/BACKLOG-21149
Failing dry-run test when releasing graphql-core https://github.com/Jahia/JahiaReleaseTool/actions/runs/8633445632/job/23668506436#step:8:9511: 
```
2024-04-10T15:56:51.4734773Z [ERROR] Failed to execute goal org.apache.maven.plugins:maven-release-plugin:2.5.3-jahia1:prepare (default-cli) on project graphql-core-root: The version could not be updated: ${parent.version} -> [Help 1]
2024-04-10T15:56:51.4742650Z org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-release-plugin:2.5.3-jahia1:prepare (default-cli) on project graphql-core-root: The version could not be updated: ${parent.version}
```
mvn needs to be able to convert to release version. Use a constant version instead.

BACKLOG-21149: Fix release issue by switching to a version constant

---

graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/DXGraphQLProvider.java

When an exception raise, there is a NPE on the getCause() when null.

BACKLOG-22906: Fix issue when uninstalling bundle and exception cause is null

---

tests/provisioning-manifest-snapshot.yml

Latest nightly failed because we could not install mvn:org.jahia.test/graphql-test-module.
I could not find it but I found mvn:org.jahia.test/**graphql-test** so I replaced it in the provisioning.
Update: I removed it from provisioning because the tests are green on release so the module doesn't seem to be necessary.

BACKLOG-23110: fix provisioning

---

tests/cypress/e2e/sdl/sdlExtensions.cy.js
tests/cypress/fixtures/sdl/sdlExtensions.js

https://jira.jahia.org/browse/SEC-104
Due to graphql-java 21.5 update https://github.com/Jahia/jahia-private/pull/2141, introspection queries are now limited to only one per query ([link](https://github.com/graphql-java/graphql-java/blob/96cadf7dc67b7905f7e960ee31e00a8373639423/src/main/java/graphql/introspection/GoodFaithIntrospection.java#L79)) otherwise it returns the error:
```
{
"errors": [
{
"message": "This request is not asking for introspection in good faith - __Type.fields is present too often!",
"extensions": {
"classification": "BadFaithIntrospection"
}
}
],
"data": null
}
```
Refactor test to query `__type` fields one at a time.

SEC-104: Fix SDL extensions test

---

graphql-dxm-provider/package.json
graphql-dxm-provider/src/javascript/registrations/playground/registerRoutes.jsx
graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/DXGraphQLProvider.java
graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/config/DXGraphQLConfig.java
graphql-dxm-provider/src/main/resources/META-INF/configurations/org.jahia.modules.graphql.provider-default.cfg
graphql-dxm-provider/src/main/resources/configs/graphqlDxmProvider.jsp
graphql-dxm-provider/src/main/resources/tools/graphql-workspace.jsp

https://jira.jahia.org/browse/SEC-104
- Disable introspection queries and graphql playground (both in developer tools and jahia tools) in production (still enabled in dev mode by default)
- Add config entry `graphql.introspection.enabled` to enable and disable for both dev and prod modes.

SEC-104: Disable introspection queries in production

---

graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/user/GqlPrincipal.java
tests/cypress/e2e/api/admin/user.cy.ts
tests/cypress/fixtures/groovy/flushCache.groovy

https://jira.jahia.org/browse/QA-15318
Prevent a `NullPointerException` when getting group memberships of a principal in GraphQL.
The list of groups are retrieved from a cache, which therefore could return a group specific to a site (i.e.: `/sites/<your site>/groups/site-users`) that no longer exists and therefore `GroupManagerService#lookupGroupByPath()` would return `null`  leading to a `NullPointerException`:
```
java.lang.NullPointerException: Cannot invoke "org.jahia.services.content.decorator.JCRGroupNode.getJahiaGroup()" because the return value of "org.jahia.services.usermanager.JahiaGroupManagerService.lookupGroupByPath(String)" is null
at org.jahia.modules.graphql.provider.dxm.user.GqlPrincipal.lambda$getGroupMembership$0(GqlPrincipal.java:50) ~[?:?]
```
The following are …

QA-15318: Prevent NPE when getting groups of a principal

---

graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/site/GqlJcrSite.java
tests/cypress/e2e/api/site.cy.ts
tests/cypress/fixtures/site/getAllSitesWithHomePage.graphql

https://jira.jahia.org/browse/QA-15289
Gracefully handle scenarios where the home page has restricted access by returning `null` for the `homePage` field of the GraphQL JCRSite query.
Depends on https://github.com/Jahia/graphql-core/pull/465.

QA-15289: GraphQL JCRSite query with restricted home page

---

tests/cypress.config.ts

https://jira.jahia.org/browse/QA-14843
Since the upgrade to Cypress 13 (in [this change](https://github.com/Jahia/graphql-core/pull/350/files#diff-c7273ca77f452520adba2dfb738cd146b83110e7faa7b861318e89b2b56b5d56R16)), the video configuration option now defaults to false and must be explicitly enabled.
See https://docs.cypress.io/app/references/changelog#13-0-0 for details.

QA-14843: Enable video for Cypress tests

---

graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/node/GqlJcrDeletedPropertyInput.java
graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/node/GqlJcrMutationSupport.java
graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/node/GqlJcrNodeMutation.java
graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/node/NodeHelper.java

Backport from v3 to support clearing multiple localized properties.

QA-15315 Backport of deletePropertiesBatch node

---

tests/cypress/e2e/api/apiDescription.cy.ts

This reverts the change to ignore `Query` done in #476 
If we ignore the entire Query node, indeed we will not get failed tests for the missing description in tools, but any other missing descriptions added while this test is disabled will be missed.
A better solution is to filter the single node missing a description.

BACKLOG-23491: Restore api description at Query level 

---

.github/workflows/nightly-RL.yml
.github/workflows/nightly-SN.yml
tests/cypress/e2e/api/admin/system.cy.ts
tests/package.json
tests/yarn.lock

https://jira.jahia.org/browse/TECH-2029
Note: For better compatibility of the tests with various environments, I could have checked for content in the string and not for the actual string. But decided to leave it as-is for the time being, we can always update the tests later on.

TECH-2029: Fixed a compatibility issue with the runtime name

---

graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/nodetype/GqlJcrNodeType.java
tests/cypress/e2e/api/jcr/nodeTypes.cy.ts
tests/schema.graphql

Closes https://github.com/Jahia/graphql-core/issues/522.
Add a new endpoint `mixinExtendsNames` in the GraphQL query to expose [the names of the mixin extends](https://github.com/Jahia/jahia-private/blob/9bb652ab56519db7666b0ef17ed4427bbc1cdb8d/core/src/main/java/org/jahia/services/content/nodetypes/ExtendedNodeType.java#L890).
Example:
```graphql
query {
jcr {
nodeTypes(filter: {includeTypes: ["jmix:categorized"]}) {
nodes {
mixinExtendsNames
}
}
}
}
```
Also sync the `schema.graphql` with the latest changes.
> [!TIP]
> Documentation to guide the reviews: [How to do a code review](https://jahia-confluence.atlassian.net/wiki/spaces/PR/pages/2064660/How+to+do+a+code+review+-+Ref+ISSOP08.A14006)

feat: Expose mixin extends names

---

graphql-dxm-provider/pom.xml

Follows https://github.com/Jahia/jahia-private/pull/4264
Allow for also using Apache Tika v3
> [!TIP]
> Documentation to guide the reviews: [How to do a code review](https://jahia-confluence.atlassian.net/wiki/spaces/PR/pages/2064660/How+to+do+a+code+review+-+Ref+ISSOP08.A14006)

chore: allow higher major version of apache tika
