Jahia/graphql-core

graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/locking/LockJCRNodeMutationExtension.java

Allow to lock and unlock nodes via mutation.
Please check if everything is as it is supposed to be.

BACKLOG-8174 Add ability to lock/unlock nodes

---

graphql-dxm-provider/pom.xml

https://jira.jahia.org/browse/BACKLOG-11952
Upgrade security-filter dependency

BACKLOG-11952: Upgrade dependency

---

graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/service/tags/GqlTagNode.java
graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/service/tags/GqlTagNodeImpl.java
graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/service/tags/GqlTagQuery.java
graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/service/tags/TagsQueryExtensions.java

https://jira.jahia.org/browse/BACKLOG-12303

BACKLOG-12303 : add tag suggestion endpoint

---

graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/service/wip/GqlJcrWipInfo.java
graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/service/wip/GqlJcrWipInfoExtension.java
graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/service/wip/GqlJcrWipInfoMutationExtension.java

https://jira.jahia.org/browse/BACKLOG-12841

BACKLOG-12841 : add WIP query jcr node field and mutation

---

graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/service/wip/GqlJcrWipInfoExtension.java
graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/service/wip/GqlJcrWipInfoMutationExtension.java

https://jira.jahia.org/browse/BACKLOG-13010

BACKLOG-13010 : add create wip mutation

---

graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/node/GqlJcrNodeImpl.java

This reverts the last commit that breaks permission check

BACKLOG-13184 : restore permission check

---

graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/node/GqlJcrNodeImpl.java

This is a second attempt at implementing this properly since the first version caused problems with system permission names.
https://jira.jahia.org/browse/BACKLOG-12896
This change is needed by the new Jahia product home page because the documentation cards might use permissions that are not deployed on some installations, such as the jExperience global access permission when jExperience is not yet deployed. Before this change it would log an exception coming from the JCRNodeWrapperImpl.hasPermission implementation which could lead users to think that something is seriously wrong when it is just a permission check on an non-declared permission which should just fail.
This change implements this at the GraphQL level to avoid changing the underlying logic for other users and …

BACKLOG-12896 - Avoid exception log if testing a permission that doesn't exist.

---

graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/node/GqlJcrProperty.java

https://jira.jahia.org/browse/QA-12458
Improve get ref node

QA-12458 improve get ref node

---

graphql-dxm-provider/pom.xml
graphql-extension-example/pom.xml
graphql-test/pom.xml
pom.xml

https://jira.jahia.org/browse/QA-12458

[QA-12458] Update module version to 1.5.0-SNAPSHOT

---

graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/node/GqlJcrProperty.java

https://jira.jahia.org/browse/QA-12458

QA-12458: Support weakreferences

---

graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/user/GqlUser.java
graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/user/UserQueryExtension.java

https://jira.jahia.org/browse/BACKLOG-13556
Just give the name of the current logged in user , and eventually its properties 
Also a beginning for  https://jira.jahia.org/browse/BACKLOG-7207

BACKLOG-13556: Added user endpoint

---

graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/node/GqlJcrProperty.java

https://jira.jahia.org/browse/QA-12458

QA-12458 fix NPE

---

graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/publication/GqlPublicationInfo.java
graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/publication/PublicationJCRNodeExtension.java
graphql-test/src/main/java/org/jahia/test/graphql/GraphQLPublicationTest.java

https://jira.jahia.org/browse/QA-12920
new graphql field with no dependency on new version of the core

QA-12920 : new GraphQL field

---

graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/node/GqlJcrMutationSupport.java
graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/node/GqlJcrProperty.java
graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/node/GqlJcrPropertyInput.java
graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/node/GqlJcrPropertyMutation.java
graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/node/GqlJcrPropertyOption.java
graphql-test/pom.xml
graphql-test/src/main/java/org/jahia/test/graphql/GraphQLNodeMutationsTest.java

https://jira.jahia.org/browse/QA-13003

QA-13003 add support for encrypted value

---

graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/node/GqlJcrProperty.java

https://jira.jahia.org/browse/QA-13003

QA-13003 remove useless logger

---

graphql-test/src/main/java/org/jahia/test/graphql/GraphQLReferencesTest.java

https://jira.jahia.org/browse/QA-12975

QA-12975 fix GraphQLReferencesTest

---

graphql-dxm-provider/src/main/resources/javascript/apps/graphql.js
graphql-dxm-provider/src/main/resources/javascript/apps/jahia.json
graphql-dxm-provider/src/main/resources/javascript/locales/de.json
graphql-dxm-provider/src/main/resources/javascript/locales/en.json
graphql-dxm-provider/src/main/resources/javascript/locales/fr.json

https://jira.jahia.org/browse/BACKLOG-14533

BACKLOG-14533

---

graphql-dxm-provider/src/main/resources/tools/graphql-playground.jsp

https://jira.jahia.org/browse/BACKLOG-14613
Just added back graphql-playground in tools, so that it's still available for administrators in production.

BACKLOG-14613: Also keep graphql-playground in tools

---

pom.xml

BACKLOG-14378 - Updated scm tag to match branch name

---

graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/site/SiteJCRNodeExtensions.java

https://jira.jahia.org/browse/SELENIUM-1270

SELENIUM-1270: Fixed error when site is null

---

graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/site/SiteJCRNodeExtensions.java

https://jira.jahia.org/browse/PROJECT-XXX

SELENIUM-1270: Allow null return

---

graphql-test/src/main/java/org/jahia/test/graphql/GraphQLPublicationTest.java

https://jira.jahia.org/browse/QA-13171

QA-13171 : waiting until the publication is finished

---

graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/node/GqlJcrQuery.java
graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/node/NodeQueryExtensions.java

https://jira.jahia.org/browse/QA-13357
Also prevent root fields to be null

QA-13357: Fixed return for nodes queries, allows null in case of error

---

.gitignore
graphql-dxm-provider/.gitignore
graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/node/GqlAdminMutation.java
graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/node/GqlAdminQuery.java
graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/node/NodeMutationExtensions.java
graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/node/NodeQueryExtensions.java

https://jira.jahia.org/browse/BACKLOG-14936
Added admin and query mutation

BACKLOG-14143 added admin mutation and query in provider

---

graphql-test/src/main/java/org/jahia/test/graphql/GraphQLNodeRetrievalTest.java
graphql-test/src/main/java/org/jahia/test/graphql/GraphQLTestSupport.java

https://jira.jahia.org/browse/QA-13357

QA-13357 : fix unit test as now we can return multiple error message.

---

graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/node/GqlAdminMutation.java
graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/node/GqlAdminQuery.java

https://jira.jahia.org/browse/BACKLOG-14944
Added version query and mutation

BACKLOG-14944 added version query and mutation

---

graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/node/GqlAdminMutation.java
graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/node/GqlAdminQuery.java

https://jira.jahia.org/browse/BACKLOG-14944
Added stub query and mutation for admin (version) not to show error in console

BACKLOG-14944 added version query and mutation (#67)

---

graphql-dxm-provider/pom.xml
graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/admin/AdminMutationExtensions.java
graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/admin/AdminQueryExtensions.java
graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/admin/GqlAdminMutation.java
graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/admin/GqlAdminQuery.java
graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/node/NodeMutationExtensions.java

https://jira.jahia.org/browse/BACKLOG-14894

BACKLOG-14894: Added export for user, remove duplicate exports clause

---

graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/admin/AdminMutationExtensions.java
graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/admin/AdminQueryExtensions.java
graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/admin/GqlAdminMutation.java
graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/admin/GqlAdminQuery.java
graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/node/NodeMutationExtensions.java

Cherry-picked admin mutations to be separated from node mutations

Cherry picked structural changes for admin nodes

---

graphql-dxm-provider/pom.xml

https://jira.jahia.org/browse/PROJECT-XXX

Export new admin package

---

graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/osgi/OSGIServiceInjectorDataFetcher.java

https://jira.jahia.org/browse/BACKLOG-14899

BACKLOG-14899: Handle inject in collections

---

graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/util/ZipUtils.java

https://jira.jahia.org/browse/QA-12762
Fix zipping folders with multiple levels of subfolders.

QA-12762: Zip file retain folder structure

---

graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/user/GqlUser.java

https://jira.jahia.org/browse/BACKLOG-14899

BACKLOG-14899: missing descriptions

---

.circleci/.circleci.settings.xml
.circleci/config.yml

Circle-ci config

---

.circleci/.circleci.settings.xml
.circleci/config.yml
.github/workflows/triggerCircleCIOnPR.yml
graphql-dxm-provider/src/main/resources/javascript/renderExample.js

QA-13444 - Fixed GraphiQL configuration to submit auth headers

---

.github/workflows/triggerCircleCIOnPr.yml

The description is in the title

Added missing github actions to ci/cd on PR

---

graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/node/GqlJcrProperty.java

https://jira.jahia.org/browse/BACKLOG-13977
Added a new property to return the binary size of the node

BACKLOG-13977: Added new property to return the binary size for a node

---

graphql-dxm-provider/pom.xml
graphql-extension-example/pom.xml
graphql-test/pom.xml
pom.xml

https://jira.jahia.org/browse/BACKLOG-15081
Rolled back to 2.2.2

BACKLOG-15081 rollback version to 2.2.2-SNAPSHOT for all files

---

graphql-dxm-provider/pom.xml
graphql-extension-example/pom.xml
graphql-test/pom.xml
pom.xml

https://jira.jahia.org/browse/BACKLOG-15081
Rolled back version

BACKLOG-15081 roll back to 2.2.2-SNAPSHOT

---

graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/predicate/SorterHelper.java

https://jira.jahia.org/browse/BACKLOG-15136
Added enum sorting

Backlog 15136 add sorting for enum

---

graphql-test/src/main/java/org/jahia/test/graphql/GraphQLNodeTypesTest.java

https://jira.jahia.org/browse/BACKLOG-15213

[BACKLOG-15213] Adapt the test following the deprecation of a node type

---

graphql-dxm-provider/pom.xml
graphql-extension-example/pom.xml
graphql-test/pom.xml
pom.xml

https://jira.jahia.org/browse/BACKLOG-15390
Prepared graphql provider for release

BACKLOG-15390 changed signature and changed version to 2.3.0-SNAPSHOT

---

graphql-test/pom.xml
graphql-test/src/main/java/org/jahia/test/graphql/GraphQLPublicationTest.java

https://jira.jahia.org/browse/BACKLOG-15343
Added some assertions and logs for more transparency regarding these failing tests

BACKLOG-15343: GraphQLPublicationTest failing randomly

---

graphql-dxm-provider/pom.xml
graphql-extension-example/pom.xml
graphql-test/pom.xml

https://jira.jahia.org/browse/BACKLOG-15343
Update signature for 2.4

BACKLOG-15343: Update Signature for version 2.4

---

graphql-dxm-provider/pom.xml
graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/instrumentation/JCRInstrumentationProvider.java
graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/instrumentation/JahiaInstrumentation.java

https://jira.jahia.org/browse/BACKLOG-15363
Allow to have custom instrumentation

BACKLOG-15363 Allow to have custom instrumentation

---

.circleci/config.yml

https://jira.jahia.org/browse/BACKLOG-15054

BACKLOG-15054: Update resource allocation

---

tests/warmup-manifest-snapshot.yml

The existing API call was searching in the SNAPSHOT repository but with a release version, which do not work. Wwe need to explicitly add the "-SNAPSHOT" suffix.

BACKLOG-15054: Fix the snapshot warmup file

---

pom.xml

https://jira.jahia.org/browse/BACKLOG-15660
This just add the version in Provide-Capability :  
```
com.jahia.modules.dependencies;moduleIdentifier=graphql-dxm-provider;moduleVersion:Version="2.4.0.SNAPSHOT",
com.jahia.modules.dependencies;moduleIdentifier="Jahia GraphQL Core Provider";moduleVersion:Version="2.4.0.SNAPSHOT"
```

BACKLOG-15660: use new plugin version

---

graphql-dxm-provider/pom.xml
graphql-extension-example/pom.xml
graphql-test/pom.xml
pom.xml

https://jira.jahia.org/browse/BACKLOG-15441
Update version and signature

Backlog 15441 version sig update

---

graphql-dxm-provider/pom.xml

https://jira.jahia.org/browse/QA-13676

QA-13676: Remove circular imports

---

tests/warmup-manifest-release.yml

I did the change in the SNAPSHOT warmup and forgot the RELEASE one

Add missing deploy step in warmup on test against release

---

graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/admin/GqlAdminQuery.java

https://jira.jahia.org/browse/BACKLOG-15994

BACKLOG-15994: Get build number

---

graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/admin/GqlAdminQuery.java

https://jira.jahia.org/browse/BACKLOG-15997

BACKLOG-15997: Removed jahia version endpoint

---

graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/user/GqlPrincipal.java
graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/user/GqlUser.java
graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/user/UserAdminExtension.java
tests/cypress/integration/api/admin/user.spec.ts

removed user admin and group entrypoints

BACKLOG-15950: Remove unprotected entrypoints

---

.circleci/.circleci.settings.xml
.circleci/config.yml
.github/workflows/triggerReleaseAction.yml
pom.xml

https://jira.jahia.org/browse/BACKLOG-16199
Prepare graphql-core `1_x` for release

BACKLOG-16199 prepare graphql-core 1_x for release

---

.circleci/.circleci.settings.xml
.circleci/config.yml
.github/workflows/triggerReleaseAction.yml
pom.xml

https://jira.jahia.org/browse/BACKLOG-16198
Added custom release job with correct artifact path, tweaked config, prepared graphql-core for github release

BACKLOG-16198 prepare graphql for release

---

graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/user/GqlUser.java
tests/cypress/fixtures/admin/group.graphql
tests/cypress/fixtures/admin/user.graphql
tests/cypress/fixtures/admin/userGroupMembershipBasic.graphql
tests/cypress/fixtures/admin/userGroupMembershipFilter.graphql
tests/cypress/fixtures/currentUser.graphql
tests/cypress/integration/api/admin/user.spec.ts
tests/cypress/integration/api/currentUser.spec.ts

https://jira.jahia.org/browse/BACKLOG-16194
Expanded user type and added some tests that properties are present

BACKLOG-16194 expand user type

---

graphql-dxm-provider/pom.xml
graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/admin/GqlJahiaAdminQuery.java
graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/admin/GqlJahiaVersion.java
graphql-extension-example/pom.xml
graphql-test/pom.xml
pom.xml

https://jira.jahia.org/browse/BACKLOG-16237
Reverted release to 1.9.1 and fixed jahia admin query, removed snapshot

BACKLOG-16237 reverted release to 1.9.1 and fixed jahia admin query, removed snapshot

---

graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/security/GqlJcrPermissionDataFetcher.java
tests/cypress/integration/api/admin/user.spec.ts
tests/cypress/integration/api/currentUser.spec.ts
tests/package.json
tests/yarn.lock

https://jira.jahia.org/browse/TECH-422
This calls the PermissionHelper on every field, not only root or field having jcr node

TECH-422: Check permission for every field

---

graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/user/GqlUserAdmin.java
graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/user/GqlUserGroup.java
graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/user/UserGroupExtension.java
tests/cypress/fixtures/admin/group.graphql
tests/cypress/integration/api/admin/user.spec.ts

Rename query.admin.userAdmin.group to query.admin.userGroup.group
https://jira.jahia.org/browse/BACKLOG-16195

BACKLOG-16195 - Rename query.admin.userAdmin.group to query.admin.userGroup.group

---

graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/node/NodeHelper.java

https://jira.jahia.org/browse/QA-13759
Simple change in hasPropertyValue() to consider multi-valued properties when querying those using graphql. Currently it is giving an internal server error instead of properly handling it.

QA-13759: Consider multivalued properties in graphql queries

---

pom.xml

https://jira.jahia.org/browse/BACKLOG-16251

BACKLOG-16251: exclude spring-core

---

graphql-dxm-provider/pom.xml
graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/DXGraphQLProvider.java
graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/JahiaDataFetchingExceptionHandler.java
graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/JahiaExecutionStrategyProvider.java
graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/JahiaMutationExecutionStrategy.java
graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/JahiaQueryExecutionStrategy.java
graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/instrumentation/JCRInstrumentation.java
graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/instrumentation/JCRInstrumentationProvider.java
graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/node/GqlJcrMutationSupport.java
graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/node/GqlJcrQuery.java
graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/predicate/FieldEvaluator.java
graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/render/RenderNodeExtensions.java
graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/security/GraphQLFieldWithPermissionRetriever.java
graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/security/PermissionHelper.java
graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/upload/UploadHelper.java
graphql-dxm-provider/src/main/resources/META-INF/configurations/graphql.kickstart.servlet.OsgiGraphQLHttpServlet.cfg
graphql-extension-example/pom.xml
graphql-test/pom.xml
graphql-test/src/main/java/org/jahia/test/graphql/GraphQLNodeMutationsTest.java
graphql-test/src/main/java/org/jahia/test/graphql/GraphQLTestSupport.java
pom.xml

https://jira.jahia.org/browse/TECH-210
* Code changes needed to sync up with the upgraded version:
```
<graphql-java.version>13.0</graphql-java.version>
<graphql-java-annotations.version>7.2.1</graphql-java-annotations.version>
<graphql-java-servlet.version>9.1.0</graphql-java-servlet.version>
```

TECH-210: Update GraphQL dependency to v13

---

pom.xml

https://jira.jahia.org/browse/QA-1359
Update jahia

QA-13595 Update pom

---

graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/node/GqlJcrProperty.java

https://jira.jahia.org/browse/DMF-4879

DMF-4879: allow to return jcr property as a boolean value

---

graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/JahiaSubscriptionExecutionStrategy.java
graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/scheduler/GqlJobListener.java
graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/scheduler/GqlJobSubscriptionExtension.java

https://jira.jahia.org/browse/TECH-483

TECH-483: set current user

---

graphql-test/pom.xml
graphql-test/src/main/java/org/jahia/test/graphql/GraphQLSchedulerTest.java
graphql-test/src/main/java/org/jahia/test/graphql/scheduler/TestJob.java

- Use websocket for test
- Fixed test

TECH-481: Fixed test

---

graphql-extension-example/pom.xml
graphql-extension-example/src/main/java/org/jahia/modules/graphql/provider/dxm/extensions/QueryExtensions.java

https://jira.jahia.org/browse/TECH-268
Sample code for async.
Can be tested by comparing the 2 queries : 
```
query q1 {
a:longField(arg:"a")
b:longField(arg:"b")
c:longField(arg:"c")
d:longField(arg:"d")
e:longField(arg:"e")
}
query q2 {
a:asyncLongField(arg:"a")
b:asyncLongField(arg:"b")
c:asyncLongField(arg:"c")
d:asyncLongField(arg:"d")
e:asyncLongField(arg:"e")
}
```

TECH-268: Added sample code

---

graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/scheduler/GqlJobSubscriptionExtension.java
graphql-test/src/main/java/org/jahia/test/graphql/GraphQLSchedulerTest.java
graphql-test/src/main/java/org/jahia/test/graphql/scheduler/TestJob.java

https://jira.jahia.org/browse/TECH-328
Add logging for further investigation

TECH-328: Add logging

---

graphql-dxm-provider/pom.xml
pom.xml

https://jira.jahia.org/browse/TECH-495

TECH-495 Specify explicit import-package

---

graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/OsgiGraphQLWsEndpoint.java
graphql-dxm-provider/src/main/resources/tools/developer/graphql-playground.jsp
graphql-test/src/main/java/org/jahia/test/graphql/GraphQLSchedulerTest.java

https://jira.jahia.org/browse/BACKLOG-16381

BACKLOG-16381: Changed websocket endpoint

---

graphql-test/src/main/java/org/jahia/test/graphql/GraphQLTestSupport.java

https://jira.jahia.org/browse/QA-13923

QA-13923 : fix port usage in test

---

.circleci/config.yml

Description is in the title, this will fix the failed nightly runs

Reverted back to default docker image for the initialize step

---

tests/ci.startup.sh

This is to make sure we're always pulling the latest images

Added a docker-compose pull to the startup script

---

tests/cypress/fixtures/jcr/getParentAndAncestors.graphql
tests/cypress/integration/api/jcr/ancestors.spec.ts
tests/cypress/integration/api/jcr/validateErrors.ts
tests/cypress/integration/api/jcr/validateNode.ts

https://jira.jahia.org/browse/BACKLOG-16497

BACKLOG-16497: Added ancestors test

---

.circleci/config.yml
tests/.eslintrc.json
tests/.graphqlconfig
tests/cypress/integration/api/admin/config.spec.ts
tests/cypress/integration/api/admin/dateTime.spec.ts
tests/cypress/integration/api/admin/user.spec.ts
tests/cypress/integration/api/admin/users.spec.ts
tests/cypress/integration/api/apiDescription.spec.ts
tests/cypress/integration/api/currentUser.spec.ts
tests/cypress/integration/api/graphqlFieldSorting.spec.ts
tests/cypress/integration/api/jcr/ancestors.spec.ts
tests/cypress/integration/api/jcr/checkNodePropertyType.spec.ts
tests/cypress/integration/api/jcr/fileGrouping.spec.ts
tests/cypress/integration/api/jcr/getNode.spec.ts
tests/cypress/integration/api/jcr/graphqlQueryTest.spec.ts
tests/cypress/integration/api/jcr/validateErrors.ts
tests/cypress/integration/api/jcr/validateNode.ts
tests/package.json
tests/yarn.lock

https://jira.jahia.org/browse/BACKLOG-16592

BACKLOG-16592 - Clean-up the CircleCI config

---

graphql-dxm-provider/pom.xml

https://jira.jahia.org/browse/BACKLOG-16526
Expose upload package for custom routines in extensions

BACKLOG-16526 Expose upload package

---

graphql-dxm-provider/pom.xml
graphql-extension-example/pom.xml

Update signature as the module has been released

BACKLOG-16678 : update signature after the release

---

graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/publication/PublicationJCRNodeMutationExtension.java
graphql-test/pom.xml
graphql-test/src/main/java/org/jahia/test/graphql/GraphQLPublicationTest.java
pom.xml

https://jira.jahia.org/browse/QA-13968

QA-13968 : add parameter to allow to publish all tree

---

graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/node/GqlJcrMutation.java
graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/node/GqlJcrMutationSupport.java

https://jira.jahia.org/browse/QA-13993

QA-13993 : add possibility to select the behaviour on import

---

graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/render/RenderNodeExtensions.java

https://jira.jahia.org/browse/BACKLOG-16851

BACKLOG-16851: Added parameters for renderedNode

---

graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/OsgiGraphQLWsEndpoint.java

https://jira.jahia.org/browse/TECH-320
New protocol to support apollo3

TECH-320: Add support for graphql-transport-ws subprotocol

---

graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/node/GqlJcrNode.java
graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/node/GqlJcrNodeImpl.java
graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/node/GqlJcrQuery.java
graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/node/NodeHelper.java
graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/node/NodeQueryExtensions.java
graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/node/SpecializedTypesHandler.java
graphql-extension-example/pom.xml
graphql-test/pom.xml
tests/package.json

https://jira.jahia.org/browse/QA-14062

QA-14062 : add locale session parameter

---

graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/util/ZipUtils.java

https://jira.jahia.org/browse/QA-14193
Update uzip method to be compatible with onedrive zips

QA-14193 Update uzip method to be compatible with onedrive zips

---

tests/.graphqlconfig
tests/cypress/fixtures/groovy/prepareValidityTest.groovy
tests/cypress/fixtures/jcr/createNodesForValidity.graphql
tests/cypress/integration/api/jcr/validityCheck.spec.ts
tests/env.local.debug.sh
tests/package.json
tests/schema.graphql
tests/yarn.lock

QA-14062 : add unit test on validity check

---

graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/util/ZipUtils.java

https://jira.jahia.org/browse/QA-13901

QA-13901: Check zipbomb before reading

---

graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/node/GqlJcrMutationSupport.java
graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/node/GqlJcrProperty.java

https://jira.jahia.org/browse/BACKLOG-17236

BACKLOG-17236: Ensure that Not_Zoned_date are saved as TZ Z (ISO8601makes Timezone offset mandatory)

---

graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/DXGraphQLProvider.java

https://jira.jahia.org/browse/TECH-809
Keep loading extensions if one is not working properly.

TECH-809 : avoid corrupted graphql extension to break schema generation

---

graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/JahiaSubscriptionExecutionStrategy.java

https://jira.jahia.org/browse/TECH-498

TECH-498: Avoid thread user reset

---

graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/node/GqlJcrMutation.java
graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/node/GqlJcrMutationSupport.java
graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/node/GqlJcrPropertyMutation.java
pom.xml

https://jira.jahia.org/browse/QA-13087, 
https://jira.jahia.org/browse/QA-14387

QA-13087, QA-14387 : validate sessions before save

---

graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/node/GqlJcrMutation.java
graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/node/GqlJcrMutationSupport.java
graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/node/GqlJcrPropertyMutation.java
pom.xml

This reverts commit 8412b5ada254848d90aa1da3c9fbfa5b8eff0fcf.
https://jira.jahia.org/browse/PROJECT-XXX

Revert "QA-13087, QA-14387 : validate sessions before save (#255)"

---

graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/service/vanity/VanityUrlMutationService.java

see https://jira.jahia.org/browse/BACKLOG-16244

BACKLOG-16244 : catch any constraint exception in vanity url mutation

---

graphql-dxm-provider/src/main/import/permissions.xml
graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/admin/AdminMutationExtensions.java
graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/admin/GqlAdminMutation.java
graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/admin/GqlAdminQuery.java
graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/sdl/parsing/SDLSchemaService.java

https://jira.jahia.org/browse/BACKLOG-17341

BACKLOG-17341 : add new permission to acess admin endpoints

---

.github/maven.settings.xml
.github/workflows/on-code-change.yml

https://jira.jahia.org/browse/TECH-835

Tech 835 fix build

---

graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/node/GqlJcrProperty.java

https://jira.jahia.org/browse/BACKLOG-19987

BACKLOG-19987: Allow to call a choicelist renderer to get a property value

---

graphql-dxm-provider/src/main/resources/resources/graphql-dxm-provider_de.properties
graphql-dxm-provider/src/main/resources/resources/graphql-dxm-provider_en.properties
graphql-dxm-provider/src/main/resources/resources/graphql-dxm-provider_fr.properties

QA-14524: Added descriptions for the admin permissions

---

graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/node/GqlJcrNode.java
graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/node/GqlJcrNodeImpl.java
graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/node/NodeHelper.java
graphql-extension-example/src/main/java/org/jahia/modules/graphql/provider/dxm/extensions/GqlNews.java

https://jira.jahia.org/browse/QA-14234

QA-14234 : use default fallback if present on the site of the node

---

graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/node/GqlJcrNodeImpl.java

https://jira.jahia.org/browse/BACKLOG-20372

BACKLOG-20372: Return parent node in case of translation reference

---

graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/render/RenderNodeExtensions.java

https://jira.jahia.org/browse/QA-14620
example code from Herve
`window.pocDocumentReact("${targetId}",{
workspace:"${renderContext.liveMode ? 'LIVE' : 'EDIT'}",
locale:"${language}",
gqlEndpoint:"${host}/modules/graphql",
documentId:"${_uuid_}"
});`

QA-14620: Ensure we set workspace in RenderContext to correctly identify live/preview/edit mode

---

graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/node/GqlJcrNode.java
graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/node/GqlJcrNodeImpl.java
graphql-test/src/main/java/org/jahia/test/graphql/GraphQLi18nTest.java

https://jira.jahia.org/browse/BACKLOG-16838
Add api to fetch languages of translations available for a node

BACKLOG-16838: Add api to fetch translation languages

---

graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/node/GqlJcrNodeImpl.java

https://jira.jahia.org/browse/BACKLOG-20371

BACKLOG-20371: Do not return references if not supported

---

graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/node/GqlJcrNodeImpl.java

https://jira.jahia.org/browse/BACKLOG-20432

BACKLOG-20432: Handle PathNotFoundException

---

graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/node/GqlJcrNodeImpl.java

https://jira.jahia.org/browse/BACKLOG-20469

BACKLOG-20469: handle referenceInField references, return parent and matching property

---

graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/util/ZipUtils.java

https://jira.jahia.org/browse/QA-14648
Takes some additional checks from https://github.com/Jahia/jahia-private/blob/master/core/src/main/java/org/jahia/ajax/gwt/helper/ZipHelper.java#L187

QA-14648: Create intermediate folders

---

graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/acl/GqlAclRole.java
graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/acl/service/JahiaAclRole.java
graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/acl/service/JahiaAclRoleProperties.java
graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/acl/service/JahiaAclService.java
graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/acl/service/JahiaAclServiceImpl.java
graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/admin/GqlAdminQuery.java
tests/cypress/e2e/api/acl/aclRoles.cy.ts
tests/cypress/fixtures/acl/getRoles.graphql
tests/cypress/fixtures/acl/removeLabels.graphql
tests/cypress/fixtures/acl/setLabels.graphql

https://jira.jahia.org/browse/BACKLOG-7508
- Adding an OSGI service for ACL queries/operations
- Adding as part of dxm-provider for now for quicker dev feedback. Might need to refactor into core later on. 
- Adding endpoint for querying roles
- Added initial cypress test

BACKLOG-7508: Add graphql query endpoint for ACL roles

---

graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/node/GqlJcrNodeImpl.java

https://jira.jahia.org/browse/QA-14732

QA-14732: Avoid error when usages is not available

---

graphql-test/pom.xml
pom.xml

https://jira.jahia.org/browse/TECH-1261
Move spring-test dependency to graphql-test

TECH-1261: Move spring-test dependency to graphql-test

---

graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/node/GqlJcrNode.java
graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/node/GqlJcrNodeImpl.java

https://jira.jahia.org/browse/BACKLOG-20786

BACKLOG-20786: Add sorter on node references

---

graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/node/GqlJcrMutation.java
graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/node/NodeMutationExtensions.java

Reverts Jahia/graphql-core#336

Revert "QA-14898 : allow to pass a language to be used in session that will s…"

---

graphql-dxm-provider/pom.xml
graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/OsgiGraphQLWsEndpoint.java

https://jira.jahia.org/browse/TECH-1009

TECH-1009: fix subscriptions

---

graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/JahiaDataFetchingExceptionHandler.java
graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/predicate/FieldEvaluator.java
tests/yarn.lock

https://jira.jahia.org/browse/TECH-1009

TECH-1009: fix error handling and FieldEvaluator

---

graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/admin/GqlClusterJournal.java

https://jira.jahia.org/browse/TECH-1284

TECH-1284: Use new service methods

---

graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/DXGraphQLProvider.java

https://jira.jahia.org/browse/BACKLOG-21603

BACKLOG-21603, TECH-1009 : remove async support

---

.github/workflows/nightly.yml

Split reporting between Jahia SN and Jahia RL

---

graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/node/GqlJcrNode.java
graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/node/GqlJcrNodeImpl.java
graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/node/GqlUsage.java

https://jira.jahia.org/browse/BACKLOG-20831
listing all properties holding references top the requested node under their parent node.
`query(
$path: String!
$language: String!
$pageSize: Int!
$currentPage: Int!
$fieldSorter: InputFieldSorterInput
) {
jcr {
nodeByPath(path: $path) {
usages: usages(
limit: $pageSize
offset: $currentPage
fieldSorter: $fieldSorter
) {
nodes {
node {
path
displayName(language: $language)
}
usages {
name
language
}
}
pageInfo {
totalCount
}
}
}
}
}`
`{
"data": {
"jcr": {
"nodeByPath": {
"usages": {
"nodes": [
{
"node": {
"path": "/sites/digitall2/home/about/area-main/rich-text-1",
"displayName": "\"Leveraging technology is our best future today.\" - Julie Hegebottom, CEO"
},
"usages": [
{
"name": "text",
"language": "en"
},
{
"name": "text",
"language": "fr"
}, …

BACKLOG-20831: Add a dedicated entry point for usages, 

---

graphql-dxm-provider/.eslintignore
graphql-dxm-provider/package.json
graphql-dxm-provider/src/javascript/tools-embed.js
graphql-dxm-provider/src/main/resources/tools/graphql-playground.jsp
graphql-dxm-provider/webpack.config.tools-embed.js

https://jira.jahia.org/browse/TECH-1477

TECH-1477: Restore graphql sandbox in tools

---

pom.xml

https://jira.jahia.org/browse/TECH-1009

TECH-1009: Use versions from jahia-parent

---

graphql-dxm-provider/package.json
graphql-dxm-provider/src/javascript/registrations/playground/registerRoutes.jsx
graphql-dxm-provider/src/javascript/tools-embed.js
graphql-dxm-provider/src/main/resources/tools/graphql-ui.jsp
graphql-dxm-provider/webpack.config.js
graphql-dxm-provider/webpack.config.tools-embed.js
graphql-dxm-provider/yarn.lock

https://jira.jahia.org/browse/BACKLOG-21805

BACKLOG-21805: Move from Apollo GraphQL Studio to GraphiQL. Rename URL to graph-ui

---

graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/content/ContentManagementGqlJcrMutationExtension.java
graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/node/GqlJcrMutation.java

https://jira.jahia.org/browse/BACKLOG-20995

BACKLOG-20995: Allow to skip nodes by nodetypes when copying

---

graphql-dxm-provider/package.json
graphql-dxm-provider/yarn.lock

https://jira.jahia.org/browse/SEC-52
Remove resolutions as it's not needed. just needed to update browserify-sign version in yarn.lock

SEC-52: Remove unneeded resolutions; update yarn.lock

---

graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/node/GqlJcrNode.java
graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/node/GqlJcrNodeImpl.java

https://jira.jahia.org/browse/BACKLOG-21965

BACKLOG-21965: add fields for file urls

---

.github/workflows/on-code-change.yml
.github/workflows/on-merge.yml
graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/node/GqlJcrNode.java
graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/node/GqlJcrNodeImpl.java

https://jira.jahia.org/browse/BACKLOG-22108

Add new entry point to manager url of external provider

---

.github/workflows/on-merge.yml
.github/workflows/on-release.yml
pom.xml

https://jira.jahia.org/browse/BACKLOG-22115
First release was not successful. Hopefully these updates will fix the pb.

BACKLOG-22115: Fix branch config

---

tests/cypress/e2e/api/apiDescription.cy.ts
tests/package.json
tests/yarn.lock

https://jira.jahia.org/browse/TECH-1631
I did not handle the part around "invalidNames" as I don't think these are useful anymore.
Added checks for Mutation and Subscriptions

TECH-1631: Moved the logic of checking the description to jahia-cypress

---

.github/workflows/on-merge.yml

https://jira.jahia.org/browse/TECH-1597
- Add missing credentials to build step https://github.com/Jahia/graphql-core/actions/runs/7848432617/job/21419566151#step:4:105
- Publish after build (we do not want to block integration test during merge)

TECH-1597: Fix 2x build - Add credentials

---

graphql-test/pom.xml

https://jira.jahia.org/browse/TECH-1597
similar to this [jira issue](https://jira.jahia.org/browse/DMF-5754?focusedId=143126&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-143126) around mock http client requiring bouncy castle but is not marked as optional.
Add import-packages as optional

TECH-1597: Fix graphql-test import-package

---

tests/provisioning-manifest-snapshot.yml

https://jira.jahia.org/browse/BACKLOG-22337
Fix failing nightly https://github.com/Jahia/graphql-core/actions/runs/7879674698/job/21500386753#step:6:2056
Add graphql-extension-example as a dependency for testing SDL extensions.

BACKLOG-22337: Install graphql-extension-example module in snapshot provisioning

---

graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/config/DXGraphQLConfig.java
graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/relay/PaginationHelper.java
graphql-dxm-provider/src/main/resources/META-INF/configurations/org.jahia.modules.graphql.provider-default.cfg

https://jira.jahia.org/browse/PROJECT-QA-15096

QA-15096: Enforce limit of 5000 nodes for one page. Log messages over 500

---

.github/workflows/nightly.yml

https://jira.jahia.org/browse/QA-15048
Nightly are missing maven to build module for SDL tests

QA-15048: Fix nightly by adding maven

---

.github/workflows/on-release.yml

https://jira.jahia.org/browse/BACKLOG-22388

BACKLOG-22388: Add new input for slack notif

---

graphql-dxm-provider/pom.xml
graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/node/GqlJcrNodeMutation.java
graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/nodetype/NodetypeJCRNodeExtensions.java

https://jira.jahia.org/browse/TECH-1416
Upgrade module to add an explicit dependency to guava (removed from transitive dependency).

TECH-1416: Upgrade Guava or stop exposing it from core

---

graphql-dxm-provider/pom.xml
graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/DXGraphQLProvider.java
graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/publication/GqlPublicationEvent.java
graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/publication/PublicationJobEventListener.java
graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/publication/PublicationJobSubscriptionExtension.java
graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/relay/PaginationHelper.java
graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/scheduler/GqlJobSubscriptionExtension.java

https://jira.jahia.org/browse/TECH-1634

TECH-1634: Add new entry point for publication job subscription and deprecate old one.

---

graphql-dxm-provider/src/javascript/tools-embed.js
graphql-dxm-provider/src/main/resources/tools/graphql-workspace.jsp

https://jira.jahia.org/browse/TECH-1735
Add context in graphql URL when using graphiql from the tools

TECH-1735 : fix graphiql in jahia tools

---

tests/jahia-module/pom.xml
tests/jahia-module/render-property-test-module/pom.xml
tests/jahia-module/sdl-test-module/pom.xml
tests/provisioning-manifest-build.yml
tests/provisioning-manifest-snapshot.yml

See the title
I've used `mvn versions:update-parent` to automatically update to the most recent release version

Update parent version in the tests

---

.github/workflows/manual-run.yml
.github/workflows/on-code-change.yml
.github/workflows/on-merge.yml
.github/workflows/on-release.yml
.github/workflows/on-rollback.yml
.github/workflows/schedule-sonar.yml

https://jira.jahia.org/browse/TECH-1639

TECH-1639: Updated GitHub Actions versions

---

graphql-dxm-provider/src/main/resources/META-INF/configurations/org.jahia.modules.graphql.provider-default.cfg

https://jira.jahia.org/browse/SEC-104
Add note requiring restart when changing introspection property

SEC-104: Add documentation regarding introspection property

---

.github/workflows/manual-run.yml

https://jira.jahia.org/browse/BACKLOG-23119

BACKLOG-23119: Backport timeout usage from master/nightly

---

.github/workflows/manual-run.yml
tests/ci.build.sh
tests/ci.startup.sh
tests/env.debug.sh
tests/env.run.sh
tests/package.json
tests/yarn.lock

https://jira.jahia.org/browse/BACKLOG-23119

BACKLOG-23119: Updated the CI to support testing of release artifacts in staging

---

.github/workflows/on-release.yml

https://jira.jahia.org/browse/BACKLOG-23269

BACKLOG-23269: Update JDK version in the release workflow

---

.github/workflows/on-release.yml

Noticed again this issue here: https://github.com/Jahia/graphql-core/actions/runs/11127315348/job/30919335946#step:5:77
https://jira.jahia.org/browse/BACKLOG-23269

BACKLOG-23269: Fix a checkout issue preventing the release

---

.github/maven.settings.xml

https://jira.jahia.org/browse/BACKLOG-23269

BACKLOG-23269: Add missing Nexus credentials

---

.github/workflows/manual-run.yml

https://jira.jahia.org/browse/BACKLOG-23269
Porting same fix from similar issue with nightly to manual run workflow: https://github.com/Jahia/graphql-core/pull/406

BACKLOG-23269: Fix issue with building test modules on manual run workflow

---

graphql-dxm-provider/src/main/java/org/jahia/modules/graphql/provider/dxm/node/GqlJcrMutationSupport.java
tests/cypress/e2e/api/apiDescription.cy.ts

This PR modifies the endpoint to delete multiple localized properties. In case one or more languages are missing, do not throw an error. This is to enable copy-to-other-languages module clearing all translations of a property at once.

QA-15315 Fail silently on deleting localized properties
